// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

import (
	"database/sql"
)

type Project struct {
	ID              string
	DisplayName     string
	CreatedAtUnixMs int64
	UpdatedAtUnixMs int64
	MetadataJson    string
	ProjectKey      string
	NextTaskSeq     int64
}

type ProjectWorkflowLink struct {
	ID               string
	ProjectID        string
	WorkflowID       string
	IsDefault        int64
	UnlinkedAtUnixMs int64
	CreatedAtUnixMs  int64
	UpdatedAtUnixMs  int64
}

type RuntimeLease struct {
	ID               string
	SessionID        string
	ClientID         string
	RequestID        string
	CreatedAtUnixMs  int64
	AcquiredAtUnixMs int64
	MetadataJson     string
}

type Session struct {
	ID                 string
	ProjectID          string
	WorkspaceID        string
	WorktreeID         sql.NullString
	ArtifactRelpath    string
	Name               string
	FirstPromptPreview string
	InputDraft         string
	ParentSessionID    string
	CreatedAtUnixMs    int64
	UpdatedAtUnixMs    int64
	LastSequence       int64
	ModelRequestCount  int64
	InFlightStep       int64
	AgentsInjected     int64
	CwdRelpath         string
	ContinuationJson   string
	LockedJson         string
	UsageStateJson     string
	MetadataJson       string
	LaunchVisible      int64
}

type Task struct {
	ID                    string
	ProjectID             string
	ProjectWorkflowLinkID string
	WorkflowID            string
	WorkflowRevisionSeen  int64
	TaskSeq               int64
	ShortID               string
	Title                 string
	Body                  string
	SourceUrl             string
	SourceWorkspaceID     sql.NullString
	ManagedWorktreeID     sql.NullString
	CanceledAtUnixMs      int64
	CancellationReason    string
	CreatedAtUnixMs       int64
	UpdatedAtUnixMs       int64
	MetadataJson          string
}

type TaskComment struct {
	ID              string
	TaskID          string
	Body            string
	AuthorKind      string
	AuthorID        string
	SourceRunID     sql.NullString
	CreatedAtUnixMs int64
	UpdatedAtUnixMs int64
	DeletedAtUnixMs int64
	MetadataJson    string
}

type TaskNodePlacement struct {
	ID                        string
	TaskID                    string
	NodeID                    string
	State                     string
	CreatedByTransitionID     sql.NullString
	ParallelBatchTransitionID sql.NullString
	ParallelBranchEdgeID      sql.NullString
	CreatedAtUnixMs           int64
	UpdatedAtUnixMs           int64
}

type TaskRun struct {
	ID                          string
	TaskID                      string
	PlacementID                 string
	NodeID                      string
	SessionID                   sql.NullString
	RunGeneration               int64
	WorkflowRevisionSeen        int64
	AutomationRequestedAtUnixMs int64
	CreatedAtUnixMs             int64
	UpdatedAtUnixMs             int64
	StartedAtUnixMs             int64
	CompletedAtUnixMs           int64
	InterruptedAtUnixMs         int64
	InterruptionReason          string
	InterruptionDetailJson      string
	WaitingAskID                string
	FinalAnswerViolationCount   int64
	InvalidCompletionCount      int64
	RunStartSnapshotJson        string
	MetadataJson                string
}

type TaskTransition struct {
	ID                    string
	TaskID                string
	SourceRunID           sql.NullString
	SourcePlacementID     sql.NullString
	SourceNodeID          sql.NullString
	SourceNodeKey         string
	SourceNodeDisplayName string
	TransitionGroupID     sql.NullString
	TransitionID          string
	TransitionDisplayName string
	WorkflowRevisionSeen  int64
	Actor                 string
	State                 string
	Commentary            string
	OutputValuesJson      string
	CreatedAtUnixMs       int64
	AppliedAtUnixMs       int64
}

type TaskTransitionEdge struct {
	ID                     string
	TaskTransitionID       string
	WorkflowEdgeID         sql.NullString
	EdgeKey                string
	WorkflowRevisionSeen   int64
	TargetNodeID           sql.NullString
	TargetNodeKey          string
	TargetNodeDisplayName  string
	TargetNodeKind         string
	TargetPlacementID      sql.NullString
	State                  string
	ContextMode            string
	RequiresApproval       int64
	InputBindingsJson      string
	OutputRequirementsJson string
	MetadataJson           string
}

type Workflow struct {
	ID              string
	Name            string
	Description     string
	GraphRevision   int64
	CreatedAtUnixMs int64
	UpdatedAtUnixMs int64
	MetadataJson    string
}

type WorkflowEdge struct {
	ID                     string
	WorkflowID             string
	TransitionGroupID      string
	EdgeKey                string
	TargetNodeID           string
	RequiresApproval       int64
	ContextMode            string
	InputBindingsJson      string
	OutputRequirementsJson string
	SortOrder              int64
	MetadataJson           string
}

type WorkflowEvent struct {
	Sequence         int64
	ProjectID        string
	WorkflowID       string
	Resource         string
	Action           string
	ChangedIdsJson   string
	OccurredAtUnixMs int64
}

type WorkflowNode struct {
	ID               string
	WorkflowID       string
	NodeKey          string
	Kind             string
	DisplayName      string
	SubagentRole     string
	PromptTemplate   string
	OutputFieldsJson string
	SortOrder        int64
	MetadataJson     string
	GroupID          sql.NullString
}

type WorkflowNodeGroup struct {
	ID           string
	WorkflowID   string
	GroupKey     string
	DisplayName  string
	SortOrder    int64
	MetadataJson string
}

type WorkflowTransitionGroup struct {
	ID           string
	WorkflowID   string
	SourceNodeID string
	TransitionID string
	DisplayName  string
	SortOrder    int64
	MetadataJson string
}

type Workspace struct {
	ID                string
	ProjectID         string
	CanonicalRootPath string
	DisplayName       string
	Availability      string
	IsPrimary         int64
	GitMetadataJson   string
	CreatedAtUnixMs   int64
	UpdatedAtUnixMs   int64
}

type Worktree struct {
	ID                string
	WorkspaceID       string
	CanonicalRootPath string
	DisplayName       string
	Availability      string
	IsMain            int64
	GitMetadataJson   string
	CreatedAtUnixMs   int64
	UpdatedAtUnixMs   int64
	BuilderManaged    int64
	CreatedBranch     int64
	OriginSessionID   string
}
