// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

import (
	"database/sql"

	"core/shared/runtimeids"
)

type MigrationCurrentNodeValueEnvironment struct {
	PlacementID            string
	CurrentInputValuesJson string
	PriorNodeValuesJson    string
	EnteredByEdgeID        string
}

type MigrationCurrentNodeValueSourceError struct {
	TaskID              string
	NodeID              string
	TransitionBranchKey sql.NullString
	PlacementID         string
	EnteringEdgeCount   int64
}

type MigrationInvalidCanceledTask struct {
	TaskID string
}

type MigrationParallelProjectionError struct {
	TaskID              string
	NodeID              sql.NullString
	TransitionBranchKey sql.NullString
	ErrorKind           string
	ErrorDetail         string
}

type MigrationPendingApprovalID struct {
	TransitionID string
	ApprovalID   string
}

type MigrationPendingApprovalProjectionError struct {
	TaskID              string
	TransitionID        string
	ExpectedBranchCount int64
	ActualHeaderCount   int64
	ActualBranchCount   int64
}

type MigrationPendingApprovalSourceError struct {
	TaskID       string
	TransitionID string
}

type MigrationPendingApprovalTargetValueEnvironment struct {
	TransitionEdgeID          string
	TargetTransitionBranchKey sql.NullString
	CurrentInputValuesJson    string
	PriorNodeValuesJson       string
	EnteredByEdgeID           string
}

type MigrationPriorValueCandidate struct {
	TaskID                    string
	ParallelBatchTransitionID sql.NullString
	TransitionBranchKey       sql.NullString
	NodeKey                   string
	TransitionKey             string
	OutputValuesJson          string
	AppliedAtUnixMs           int64
	CreatedAtUnixMs           int64
	TransitionRecordID        string
}

type MigrationSessionMetadataError struct {
	SessionID string
}

type MigrationSessionTaskError struct {
	SessionID string
	TaskCount int64
}

type MigrationUnfinishedCurrentNodeError struct {
	TaskID              string
	NodeID              string
	TransitionBranchKey sql.NullString
	UnfinishedRunCount  int64
}

type MigrationWorkflowGraphEdge struct {
	WorkflowID     string
	EdgeID         string
	TransitionKey  string
	SourceNodeID   string
	SourceNodeKey  string
	SourceNodeKind string
	TargetNodeID   string
	TargetNodeKey  string
	TargetNodeKind string
	PromptTemplate string
	ParametersJson string
}

type Project struct {
	ID                           string
	DisplayName                  string
	CreatedAtUnixMs              int64
	UpdatedAtUnixMs              int64
	MetadataJson                 string
	ProjectKey                   string
	NextTaskSeq                  int64
	DefaultProjectWorkflowLinkID sql.NullString
	PrimaryWorkspaceID           string
}

type ProjectDefaultWorkflowIdentity struct {
	ProjectID    string
	WorkflowID   *runtimeids.WorkflowID
	WorkflowName sql.NullString
}

type ProjectLabel struct {
	ID              string
	ProjectID       string
	Name            string
	CreatedAtUnixMs int64
	UpdatedAtUnixMs int64
	Ordinal         int64
}

type ProjectWorkflowLink struct {
	ID              string
	ProjectID       string
	WorkflowID      runtimeids.WorkflowID
	CreatedAtUnixMs int64
	UpdatedAtUnixMs int64
}

type ProjectWorkflowLinkRecord struct {
	ID              string
	ProjectID       string
	WorkflowID      runtimeids.WorkflowID
	IsDefault       int64
	CreatedAtUnixMs int64
	UpdatedAtUnixMs int64
}

type Session struct {
	ID                       string
	ProjectID                string
	WorkspaceID              sql.NullString
	WorktreeID               sql.NullString
	ArtifactRelpath          string
	Name                     string
	FirstPromptPreview       string
	InputDraft               string
	Category                 sql.NullString
	CreatedAtUnixMs          int64
	UpdatedAtUnixMs          int64
	LastSequence             int64
	ModelRequestCount        int64
	LaunchVisible            int64
	CwdRelpath               string
	ContinuationJson         string
	LockedJson               string
	UsageStateJson           string
	MetadataJson             string
	PreviousSessionID        sql.NullString
	ParentAgentSessionID     sql.NullString
	TaskID                   sql.NullString
	CompletedCompactionCount sql.NullInt64
	ManualCompactEligible    sql.NullInt64
	ProtectedInputDraft      sql.NullString
}

type SessionPromptHistoryEntry struct {
	Sequence        int64
	SessionID       string
	Text            string
	CreatedAtUnixMs int64
}

type SessionWorkflowNodeAssociation struct {
	SessionID           string
	NodeID              string
	TransitionBranchKey sql.NullString
	AssociatedAtUnixMs  int64
}

type SqliteSchema struct {
	Type string
	Name string
	Sql  sql.NullString
}

type Task struct {
	ID                              string
	ProjectWorkflowLinkID           string
	WorkflowRevisionSeen            int64
	TaskSeq                         int64
	ShortID                         string
	Title                           string
	Body                            string
	SourceUrl                       string
	SourceWorkspaceID               sql.NullString
	ManagedWorktreeID               sql.NullString
	ExecutionTargetMode             sql.NullString
	ExecutionTargetRequestedRef     sql.NullString
	ExecutionTargetResolvedRef      sql.NullString
	ExecutionTargetCommitOid        sql.NullString
	ExecutionTargetProvenance       sql.NullString
	CreatedAtUnixMs                 int64
	UpdatedAtUnixMs                 int64
	MetadataJson                    string
	PendingInitialManagedBranchName sql.NullString
}

type TaskActiveFanout struct {
	TaskID string
}

type TaskActiveFanoutBranch struct {
	TaskID              string
	TransitionBranchKey string
	ArrivalState        string
	ArrivalValuesJson   sql.NullString
}

type TaskComment struct {
	ID              string
	TaskID          string
	Body            string
	AuthorKind      string
	AuthorID        string
	CreatedAtUnixMs int64
	UpdatedAtUnixMs int64
}

type TaskCurrentNode struct {
	TaskID                 string
	NodeID                 string
	TransitionBranchKey    sql.NullString
	CurrentInputValuesJson string
	PriorNodeValuesJson    string
	SessionID              sql.NullString
	SchedulingState        sql.NullString
	InterruptionReason     sql.NullString
	InterruptionDetailJson sql.NullString
	InterruptedAtUnixMs    sql.NullInt64
	EnteredByEdgeID        sql.NullString
	EffectiveAssignee      sql.NullString
	EffectiveThinking      sql.NullString
	AssigneeOrigin         sql.NullString
}

type TaskDependency struct {
	BlockerTaskID string
	BlockedTaskID string
}

type TaskLabelAssignment struct {
	TaskID  string
	LabelID string
}

type TaskPendingApproval struct {
	ID                        string
	SourceTaskID              string
	SourceNodeID              string
	SourceTransitionBranchKey sql.NullString
	SourceSessionID           sql.NullString
	WorkflowVersion           int64
	TransitionSnapshotJson    string
	MaterializedValuesJson    string
	CreatedAtUnixMs           int64
}

type TaskPendingApprovalBranch struct {
	ApprovalID                     string
	TransitionBranchKey            string
	TargetSnapshotJson             string
	EffectiveEdgeConfigurationJson string
	ContextSourceResolutionJson    string
}

type TaskRecord struct {
	ID                              string
	ProjectID                       string
	ProjectWorkflowLinkID           string
	WorkflowID                      runtimeids.WorkflowID
	WorkflowRevisionSeen            int64
	TaskSeq                         int64
	ShortID                         string
	Title                           string
	Body                            string
	SourceUrl                       string
	SourceWorkspaceID               sql.NullString
	ManagedWorktreeID               sql.NullString
	PendingInitialManagedBranchName sql.NullString
	ExecutionTargetMode             sql.NullString
	ExecutionTargetRequestedRef     sql.NullString
	ExecutionTargetResolvedRef      sql.NullString
	ExecutionTargetCommitOid        sql.NullString
	ExecutionTargetProvenance       sql.NullString
	CreatedAtUnixMs                 int64
	UpdatedAtUnixMs                 int64
	MetadataJson                    string
}

type TaskSearchContent struct {
	DocumentID int64
	ShortID    interface{}
	Title      interface{}
	Body       interface{}
	Comment    interface{}
}

type TaskSearchDocument struct {
	DocumentID int64
	SourceKind string
	TaskID     sql.NullString
	CommentID  sql.NullString
}

type TaskSearchFt struct {
	Title         string
	Body          string
	Comment       string
	Rank          sql.NullFloat64
	TaskSearchFts sql.NullString
}

type TaskSearchShortIDFt struct {
	ShortID string
}

type Workflow struct {
	ID                       runtimeids.WorkflowID
	Name                     string
	Description              string
	Version                  int64
	ExecutionTargetPolicy    string
	ExecutionTargetCustomRef sql.NullString
	CreatedAtUnixMs          int64
	UpdatedAtUnixMs          int64
}

type WorkflowEdge struct {
	ID                     string
	TransitionGroupID      string
	EdgeKey                string
	TargetNodeID           string
	RequiresApproval       int64
	ContextMode            string
	InputBindingsJson      string
	OutputRequirementsJson string
	SortOrder              int64
	ContextSourceKind      string
	ContextSourceNodeKey   string
	PromptTemplate         string
	ParametersJson         string
	AssigneeSelection      string
	ThinkingSelection      string
}

type WorkflowNode struct {
	ID                     string
	WorkflowID             runtimeids.WorkflowID
	NodeKey                string
	Kind                   string
	DisplayName            string
	SubagentRole           string
	GroupID                sql.NullString
	SortOrder              int64
	JoinInputProvidersJson string
	CompletionMode         string
	ScriptPath             sql.NullString
}

type WorkflowNodeGroup struct {
	ID          string
	WorkflowID  runtimeids.WorkflowID
	GroupKey    string
	DisplayName string
	SortOrder   int64
}

type WorkflowTaskStatusRecord struct {
	TaskID             string
	IsDone             int64
	Kind               string
	PrimaryStatusRank  int64
	NodeIdsJson        interface{}
	AttentionTypesJson interface{}
}

type WorkflowTransitionGroup struct {
	ID           string
	SourceNodeID string
	TransitionID string
	DisplayName  string
	SortOrder    int64
	Description  string
}

type Workspace struct {
	ID                string
	ProjectID         string
	CanonicalRootPath string
	GitMetadataJson   string
	CreatedAtUnixMs   int64
	UpdatedAtUnixMs   int64
}

type Worktree struct {
	ID                    string
	WorkspaceID           string
	CanonicalRootPath     string
	Managed               int64
	CreatedBranch         int64
	OriginSessionID       string
	GitMetadataJson       string
	CreatedAtUnixMs       int64
	UpdatedAtUnixMs       int64
	CreationBaseCommitOid sql.NullString
}
