# frozen_string_literal: true

# Hand-written, DEPRECATED Homebrew formula for the Builder -> Kent migration.
#
# This is the canonical source for `Formula/builder-cli.rb` in the
# respawn-llc/homebrew-tap repo. It is published MANUALLY (copied into the tap),
# NOT regenerated by scripts/update-brew-tap.sh or the release workflow — those
# now only produce the `kent` formula.
#
# It builds the Builder 2.0 migration-only compat binary from the builder-2.0.0
# tag of respawn-llc/kent. That binary refuses to start and only runs
# `builder migrate` and `builder service uninstall`.
#
# IMPORTANT: do NOT add `depends_on "kent"`. A dependency marks kent as
# installed-as-dependency, so a later `brew autoremove` (after the user
# uninstalls builder-cli) would delete the real kent binary. Users install kent
# explicitly. There is also intentionally NO post_install service-restart hook.
#
# Retirement: keep `deprecate!` (installable, warns) during the ~1-month
# migration window, then `disable!`, then remove the formula.
class BuilderCli < Formula
  desc "Migration-only build to move from Builder to Kent (deprecated)"
  homepage "https://kent.sh/"
  url "https://github.com/respawn-llc/kent/archive/refs/tags/builder-2.0.0.tar.gz"
  sha256 "REPLACE_WITH_builder-2.0.0_TARBALL_SHA256"
  license "AGPL-3.0-only"

  # Replacement is the `kent` formula; users install it explicitly.
  deprecate! date: "2026-06-14", because: "Builder was renamed to Kent; run `builder migrate`, then install `kent`"

  depends_on "go" => :build
  depends_on "git"

  def install
    ENV["BUILDER_VERSION"] = "2.0.0"
    ENV["BUILDER_SKIP_FRONTEND"] = "1"
    system "bash", "scripts/build.sh", "--output", bin/"builder", "--skip-frontend"
  end

  def caveats
    <<~EOS
      Builder has been renamed to Kent. This is the migration-only build; it does
      not start a server or run agents.

      To migrate (run these yourself — migration is never automatic):
        1. Stop all Builder activity (interactive sessions, `builder serve`, and
           `builder service stop` if the background service is installed).
        2. Move + rebase your data:   builder migrate
        3. Install Kent:              brew install respawn-llc/homebrew-tap/kent
        4. Remove this formula:       brew uninstall builder-cli

      Migration guide: https://kent.sh/
    EOS
  end

  test do
    output = shell_output("#{bin}/builder 2>&1", 1)
    assert_match "renamed to Kent", output
  end
end
