export const queryKeys = {
  startup: ["startup"],
  readiness: ["startup", "readiness"],
  projects: ["projects"],
  allProjectEdits: ["project-edit"],
  projectEdit: (projectID: string) => ["project-edit", projectID],
  attention: (projectID: string) => ["attention", projectID],
  allWorkspaces: ["workspaces"],
  workspaces: (projectID: string) => ["workspaces", projectID],
  allAttention: ["attention"],
  allBoards: ["board"],
  allTasks: ["task"],
  allActivity: ["activity"],
  allPendingAsks: ["pending-asks"],
  board: (projectID: string, workflowID: string) => ["board", projectID, workflowID],
  task: (taskID: string) => ["task", taskID],
  activity: (taskID: string) => ["activity", taskID],
  pendingAsks: (sessionID: string) => ["pending-asks", sessionID],
};
