package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"core/shared/serverapi"
)

const (
	queriesFilename              = "queries.sql.tmpl"
	taskLabelFilterFilename      = "task_label_filter.sql.tmpl"
	taskDependencyFilterFilename = "task_dependency_filter.sql.tmpl"
	taskStatusProjectionFilename = "task_status_projection.sql.tmpl"
)

type QuerySourceRenderer struct {
	queries              []byte
	taskLabelFilter      []byte
	taskDependencyFilter []byte
	taskStatusProjection []byte
}

func LoadQuerySourceRenderer(directory string) (QuerySourceRenderer, error) {
	read := func(filename string) ([]byte, error) {
		path := filepath.Join(directory, filename)
		source, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read metadata query source %s: %w", path, err)
		}
		return source, nil
	}
	queries, err := read(queriesFilename)
	if err != nil {
		return QuerySourceRenderer{}, err
	}
	labelFilter, err := read(taskLabelFilterFilename)
	if err != nil {
		return QuerySourceRenderer{}, err
	}
	dependencyFilter, err := read(taskDependencyFilterFilename)
	if err != nil {
		return QuerySourceRenderer{}, err
	}
	statusProjection, err := read(taskStatusProjectionFilename)
	if err != nil {
		return QuerySourceRenderer{}, err
	}
	return QuerySourceRenderer{
		queries:              queries,
		taskLabelFilter:      labelFilter,
		taskDependencyFilter: dependencyFilter,
		taskStatusProjection: statusProjection,
	}, nil
}

func (r QuerySourceRenderer) Render() ([]byte, error) {
	queryTemplate, err := r.parse()
	if err != nil {
		return nil, err
	}
	var generated bytes.Buffer
	if err := queryTemplate.Execute(&generated, renderData{
		TaskListSortSlots: taskListSortSlots(),
		TaskGroups:        taskGroupTemplateData(),
	}); err != nil {
		return nil, fmt.Errorf("render metadata query template: %w", err)
	}
	return append(bytes.TrimRight(generated.Bytes(), "\n"), '\n'), nil
}

func (r QuerySourceRenderer) RenderTaskSearchPageDescriptors() ([]byte, error) {
	return r.renderTaskSearchQuery("taskSearchPageDescriptors", true)
}

func (r QuerySourceRenderer) RenderTaskSearchSchemaContract() ([]byte, error) {
	return r.renderTaskSearchQuery("taskSearchSchemaContract", false)
}

type taskLabelFilterTemplateData struct {
	FilterKind       string
	FilterMode       string
	Indent           string
	LabelIDs         string
	ExcludedLabelIDs string
	TaskID           string
}

type taskDependencyFilterTemplateData struct {
	DependencyFilter string
	Indent           string
	TaskID           string
}

type taskStatusProjectionTemplateData struct {
	LiveTaskStatesJSON string
	Indent             string
	Suffix             string
}

type taskListSortSlotTemplateData struct {
	Index int
	Last  bool
}

type renderData struct {
	IncludeTaskSearchPageDescriptors bool
	TaskListSortSlots                []taskListSortSlotTemplateData
	TaskGroups                       []taskGroupSQLTemplateData
}

type taskGroupSQLTemplateData struct {
	Name        string
	StatusKinds []string
}

func taskGroupTemplateData() []taskGroupSQLTemplateData {
	definitions := serverapi.WorkflowProjectTaskGroupDefinitions()
	groups := make([]taskGroupSQLTemplateData, len(definitions))
	for index, definition := range definitions {
		statusKinds := make([]string, len(definition.StatusKinds))
		for statusIndex, status := range definition.StatusKinds {
			statusKinds[statusIndex] = string(status)
		}
		groups[index] = taskGroupSQLTemplateData{Name: string(definition.Group), StatusKinds: statusKinds}
	}
	return groups
}

func taskListSortSlots() []taskListSortSlotTemplateData {
	slots := make([]taskListSortSlotTemplateData, serverapi.WorkflowTaskListMaxSortSelectors)
	for index := range slots {
		slots[index] = taskListSortSlotTemplateData{
			Index: index + 1,
			Last:  index == len(slots)-1,
		}
	}
	return slots
}

func (r QuerySourceRenderer) renderTaskSearchQuery(templateName string, includePageDescriptors bool) ([]byte, error) {
	return r.renderNamedQuery(templateName, renderData{
		IncludeTaskSearchPageDescriptors: includePageDescriptors,
	})
}

func (r QuerySourceRenderer) renderNamedQuery(templateName string, data renderData) ([]byte, error) {
	queryTemplate, err := r.parse()
	if err != nil {
		return nil, err
	}
	query := queryTemplate.Lookup(templateName)
	if query == nil {
		return nil, fmt.Errorf("task-search query template %q is absent", templateName)
	}
	var rendered bytes.Buffer
	if err := query.Execute(&rendered, data); err != nil {
		return nil, fmt.Errorf("render metadata query template %q: %w", templateName, err)
	}
	return rendered.Bytes(), nil
}

func (r QuerySourceRenderer) parse() (*template.Template, error) {
	filterTemplate, err := template.New("task_label_filter").
		Option("missingkey=error").
		Parse(string(r.taskLabelFilter))
	if err != nil {
		return nil, fmt.Errorf("parse task label filter template: %w", err)
	}
	dependencyTemplate, err := template.New("task_dependency_filter").
		Option("missingkey=error").
		Parse(string(r.taskDependencyFilter))
	if err != nil {
		return nil, fmt.Errorf("parse task dependency filter template: %w", err)
	}
	statusTemplate, err := template.New("task_status_projection").
		Option("missingkey=error").
		Parse(string(r.taskStatusProjection))
	if err != nil {
		return nil, fmt.Errorf("parse task status projection template: %w", err)
	}
	renderTaskLabelFilter := func(
		indent string,
		taskID string,
		filterKind string,
		filterMode string,
		labelIDs string,
		excludedLabelIDs string,
	) (string, error) {
		data := taskLabelFilterTemplateData{
			FilterKind:       filterKind,
			FilterMode:       filterMode,
			Indent:           indent,
			LabelIDs:         labelIDs,
			ExcludedLabelIDs: excludedLabelIDs,
			TaskID:           taskID,
		}
		if err := data.validate(); err != nil {
			return "", err
		}
		var rendered bytes.Buffer
		if err := filterTemplate.Execute(&rendered, data); err != nil {
			return "", fmt.Errorf("render task label filter template: %w", err)
		}
		return rendered.String(), nil
	}
	renderTaskStatusProjection := func(
		indent string,
		liveTaskStatesJSON string,
		suffix string,
	) (string, error) {
		data := taskStatusProjectionTemplateData{
			LiveTaskStatesJSON: liveTaskStatesJSON,
			Indent:             indent,
			Suffix:             suffix,
		}
		if err := data.validate(); err != nil {
			return "", err
		}
		var rendered bytes.Buffer
		if err := statusTemplate.Execute(&rendered, data); err != nil {
			return "", fmt.Errorf("render task status projection template: %w", err)
		}
		return rendered.String(), nil
	}
	renderTaskDependencyFilter := func(indent string, taskID string, dependencyFilter string) (string, error) {
		data := taskDependencyFilterTemplateData{
			DependencyFilter: dependencyFilter,
			Indent:           indent,
			TaskID:           taskID,
		}
		if err := data.validate(); err != nil {
			return "", err
		}
		var rendered bytes.Buffer
		if err := dependencyTemplate.Execute(&rendered, data); err != nil {
			return "", fmt.Errorf("render task dependency filter template: %w", err)
		}
		return rendered.String(), nil
	}
	queryTemplate, err := template.New("queries").
		Option("missingkey=error").
		Funcs(template.FuncMap{
			"taskLabelFilter":      renderTaskLabelFilter,
			"taskDependencyFilter": renderTaskDependencyFilter,
			"taskStatusProjection": renderTaskStatusProjection,
		}).
		Parse(string(r.queries))
	if err != nil {
		return nil, fmt.Errorf("parse metadata query template: %w", err)
	}
	return queryTemplate, nil
}

func (d taskDependencyFilterTemplateData) validate() error {
	switch {
	case strings.TrimSpace(d.TaskID) == "":
		return errors.New("task ID template expression is empty")
	case strings.TrimSpace(d.DependencyFilter) == "":
		return errors.New("dependency filter template expression is empty")
	default:
		return nil
	}
}

func (d taskLabelFilterTemplateData) validate() error {
	switch {
	case strings.TrimSpace(d.TaskID) == "":
		return errors.New("task ID template expression is empty")
	case strings.TrimSpace(d.FilterKind) == "":
		return errors.New("filter kind template expression is empty")
	case strings.TrimSpace(d.FilterMode) == "":
		return errors.New("filter mode template expression is empty")
	case strings.TrimSpace(d.LabelIDs) == "":
		return errors.New("label IDs template expression is empty")
	case strings.TrimSpace(d.ExcludedLabelIDs) == "":
		return errors.New("excluded label IDs template expression is empty")
	default:
		return nil
	}
}

func (d taskStatusProjectionTemplateData) validate() error {
	switch {
	case strings.TrimSpace(d.LiveTaskStatesJSON) == "":
		return errors.New("live task states JSON template expression is empty")
	case d.Suffix != "" && d.Suffix != ",":
		return fmt.Errorf("task status projection suffix %q is invalid", d.Suffix)
	default:
		return nil
	}
}
